name: auth_socmed
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8
  cloud_firestore: ^4.4.4
  shared_preferences: ^2.0.18
  http: ^0.13.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  #  Hahaha123!
# VzSiQcXRmi2kyjzcA+mYLEtbGVs=

